name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd eco-clean
          git pull
          sudo docker stop eco-clean || true
          sudo docker rm eco-clean || true
          sudo docker build -t eco-clean .
          sudo docker run -d -p 80:3000 eco-clean